Repository RD2W/practicum-android-diploma, pull requests merged in 2025-06, with the labels that each got.

#35 Data и Domain слои для [EPIC_1] Поиск вакансий и [EPIC_2] Детали вакансии
  app/src/main/java/ru/practicum/android/diploma/common/constants/AppConstants.kt
  app/src/main/java/ru/practicum/android/diploma/common/domain/model/RequestResult.kt
  app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt
  app/src/main/java/ru/practicum/android/diploma/di/DomainModule.kt
  app/src/main/java/ru/practicum/android/diploma/di/SourceModule.kt
  app/src/main/java/ru/practicum/android/diploma/filter/data/repository/AreasListGetterImpl.kt
  app/src/main/java/ru/practicum/android/diploma/filter/data/repository/CountriesListGetterImpl.kt
  app/src/main/java/ru/practicum/android/diploma/filter/data/repository/IndustriesListGetterImpl.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/mapper/SearchParametersMapper.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/mapper/SearchResultMapper.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/mapper/VacancyDetailsMapper.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/mapper/VacancyMapper.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/model/HHApiRequest.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/model/HHApiResponse.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/model/dto/VacancyAreaDto.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/model/dto/VacancyDetailsDto.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/model/dto/VacancyDto.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/repository/VacanciesGetterImpl.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/source/remote/HHApiLoggingInterceptor.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/source/remote/HHApiResponse.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/source/remote/HHApiService.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/source/remote/NetworkClient.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/source/remote/RetrofitClient.kt
  app/src/main/java/ru/practicum/android/diploma/search/domain/model/SearchParameters.kt
  app/src/main/java/ru/practicum/android/diploma/search/domain/model/SearchResult.kt
  app/src/main/java/ru/practicum/android/diploma/search/domain/repository/SearchRepository.kt
  app/src/main/java/ru/practicum/android/diploma/search/domain/usecase/SearchUseCase.kt
  app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/domain/usecase/GetVacancyDetailsUseCase.kt
Labels: EPIC_1, EPIC_2

#39 [EPIC_2] Реализовать бизнес логику для экрана "Вакансия"
  app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt
  app/src/main/java/ru/practicum/android/diploma/di/DomainModule.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/mapper/VacancyDetailsMapper.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/search/domain/repository/SearchRepository.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/data/repository/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/vacancy/data/repository/VacancyDetailsRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/domain/model/Result.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/domain/repository/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/vacancy/domain/repository/VacancyDetailsRepository.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/domain/usecase/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/vacancy/domain/usecase/GetVacancyDetailsByIdUseCase.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/domain/usecase/GetVacancyDetailsUseCase.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/domain/usecase/ShareVacancyUseCase.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/domain/usecase/impl/GetVacancyDetailsByIdUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/domain/usecase/impl/ShareVacancyUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/presentation/state/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/vacancy/presentation/state/VacancyDetailsState.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/presentation/state/VacancyErrorType.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/presentation/view/VacancyFragment.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/presentation/viewmodel/VacancyViewModel.kt
Labels: EPIC_2

#41 [EPIC_3] Реализация функционала "поделиться" и добавления в избранное на экране "Вакансии"
  app/src/main/java/ru/practicum/android/diploma/favorites/data/mapper/MapperDbEntities.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/data/source/local/db/entity/FavoriteVacancyEntity.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/mapper/VacancyDetailsMapper.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/domain/model/VacancyDetails.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/presentation/view/VacancyFragment.kt
Labels: EPIC_2

#43 [Epic1] Настройка слоя presentation для экрана Поиск вакансий
  app/src/main/java/ru/practicum/android/diploma/common/presentation/adapter/VacancyViewHolder.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/mapper/VacancyMapper.kt
  app/src/main/java/ru/practicum/android/diploma/search/presentation/adapter/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/search/presentation/adapter/DiffCallback.kt
  app/src/main/java/ru/practicum/android/diploma/search/presentation/adapter/ListItem.kt
  app/src/main/java/ru/practicum/android/diploma/search/presentation/adapter/LoadingViewHolder.kt
  app/src/main/java/ru/practicum/android/diploma/search/presentation/adapter/VacancyLoadMoreAdapter.kt
  app/src/main/java/ru/practicum/android/diploma/search/presentation/state/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/search/presentation/state/SearchVacanciesScreenState.kt
  app/src/main/java/ru/practicum/android/diploma/search/presentation/view/SearchFragment.kt
  app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt
  app/src/main/res/drawable/ic_background_vacancy.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_loading.xml
  app/src/main/res/layout/item_vacancy.xml
  app/src/main/res/values-night-v27/themes.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-ru-rRU/plurals.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-v27/themes.xml
  app/src/main/res/values/plurals.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: EPIC_1

#28 Epic0/vacancy xml
  app/src/main/java/ru/practicum/android/diploma/common/utils/FormatStrings.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/mapper/VacancyDetailsMapper.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/model/HHApiResponse.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/model/dto/SkillDto.kt
  app/src/main/java/ru/practicum/android/diploma/team/presentation/view/TeamFragment.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/presentation/view/VacancyFragment.kt
  app/src/main/res/drawable/ic_vacancy_placeholder.xml
  app/src/main/res/layout/fragment_vacancy.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/menu/top_appbar_menu.xml
  app/src/main/res/values-night-v28/styles.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-v28/styles.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: EPIC_1

#63 [REVIEW_FIXES] Исправление общих замечаний по коду приложения
  app/src/main/java/ru/practicum/android/diploma/common/constants/AppConstants.kt
  app/src/main/java/ru/practicum/android/diploma/common/domain/model/RequestResult.kt
  app/src/main/java/ru/practicum/android/diploma/country/domain/usecase/impl/GetCountriesListUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/country/presentation/view/CountryFragment.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/domain/usecase/impl/AddToFavoriteUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/domain/usecase/impl/CheckIsFavoriteUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/domain/usecase/impl/GetFavoriteVacanciesUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/domain/usecase/impl/GetFavoriteVacancyByIdUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/domain/usecase/impl/RemoveFromFavoriteUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/domain/usecase/impl/ToggleFavoriteStatusUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/presentation/viewmodel/FavoritesViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/filter/data/mapper/CountryMapper.kt
  app/src/main/java/ru/practicum/android/diploma/filter/data/mapper/IndustryMapper.kt
  app/src/main/java/ru/practicum/android/diploma/filter/domain/usecase/impl/CheckFilterLoadUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/filter/domain/usecase/impl/GetFilterUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/filter/domain/usecase/impl/SetFilterUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/view/FilterFragment.kt
  app/src/main/java/ru/practicum/android/diploma/industry/domain/usecase/impl/GetIndustriesListUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/industry/presentation/view/IndustryFragment.kt
  app/src/main/java/ru/practicum/android/diploma/region/domain/usecase/impl/GetAreasListUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/region/presentation/view/RegionFragment.kt
  app/src/main/java/ru/practicum/android/diploma/search/domain/usecase/impl/SearchUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/search/presentation/view/SearchFragment.kt
  app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/team/domain/usecase/impl/GetDevTeamUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/team/domain/usecase/impl/OpenGithubProfileUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/data/repository/VacancyDetailsRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/domain/usecase/impl/GetVacancyDetailsByIdUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/domain/usecase/impl/ShareVacancyUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/vacancy/presentation/viewmodel/VacancyViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/workplace/presentation/view/WorkplaceFragment.kt
Labels: EPIC_1, EPIC_2, EPIC_3

#70 Исправление UI на экране выбора отрасли
  app/src/main/java/ru/practicum/android/diploma/industry/presentation/adapter/IndustriesAdapter.kt
  app/src/main/java/ru/practicum/android/diploma/industry/presentation/view/IndustryFragment.kt
Labels: bug, EPIC_4

#72 [REVIEW_FIXES] BugFix: исправить поведение UI на экране "Выбор места работы"
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/view/FilterFragment.kt
  app/src/main/java/ru/practicum/android/diploma/workplace/presentation/view/WorkplaceFragment.kt
Labels: bug, EPIC_5, REVIEW_FIXES

#73 [REVIEW_FIXES] BugFix: логика автоматического сохранения любых изменений в настройках фильтра
  app/src/main/java/ru/practicum/android/diploma/common/constants/AppConstants.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/view/FilterFragment.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/viewmodel/FilterViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/search/presentation/view/SearchFragment.kt
  app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt
Labels: EPIC_4, EPIC_5, REVIEW_FIXES

#74 Iteration 4 review
  app/src/main/java/ru/practicum/android/diploma/common/constants/AppConstants.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/view/FilterFragment.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/viewmodel/FilterViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/industry/presentation/adapter/IndustriesAdapter.kt
  app/src/main/java/ru/practicum/android/diploma/industry/presentation/view/IndustryFragment.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/mapper/MapperDto.kt
  app/src/main/java/ru/practicum/android/diploma/search/presentation/view/SearchFragment.kt
  app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/workplace/presentation/view/WorkplaceFragment.kt
Labels: REVIEW_FIXES
